### User sign up endpoint 
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "ravi",
    "company":"Company name",
    "address": "Dharuhera",
    "phone": "123456789",
    "email": "ravi@gmail.com",
    "password": "ravi123"
}
### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{

    "email": "ravi@gmail.com",
    "password": "password1"
}


### Get a user profile endpoint 
 GET http://localhost:3001/v1/user
 Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhdmlAZ21haWwuY29tIiwiaWF0IjoxNzIxNDgxNTYyLCJleHAiOjE3MjE0ODE2MjJ9.wroftedMGsAqs2HF9yxlXDnUvpi3xrVQD-UprL9fJe0


## Token routers

## Get refreshed token
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhdmlAZ21haWwuY29tIiwiaWF0IjoxNzIxNDc4OTA2LCJleHAiOjE3MjQwNzA5MDZ9.zHj4lYNbOUszTbwiqOpQUsHPx7adxIJaoW3S7uEQNvc


### Password reset request endpoint
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{

    "email": "ravi@gmail.com"
  
}

### Updated new password endpoint
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{

    "email": "ravi@gmail.com",
    "pin" : "957546",
    "newPassword" : "password1"
  
}

### User logout endpoint
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhdmlAZ21haWwuY29tIiwiaWF0IjoxNzIxNTg3MDMwLCJleHAiOjE3MjE1ODc5MzB9.4fPR2-Fw00XzFQNrxs7GxEdhJW5HdREWKSU_MLUDtyg