### User sign up endpoint 
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "jatin",
    "company":"Company name",
    "address": "Dharuhera",
    "phone": "123456789",
    "email": "manish@gmail.com",
    "password": "manish123"
}
### User sign in endpoint 
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{

    "email": "manish@gmail.com",
    "password": "manish123"
}