### User sign up endpoint 
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "ravi",
    "company":"Company name",
    "address": "Dharuhera",
    "phone": "123456789",
    "email": "ravi@gmail.com",
    "password": "ravi123"
}
### User sign in endpoint 
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{

    "email": "manish@gmail.com",
    "password": "manish123"
}
### Get a user profile endpoint 
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbmlzaEBnbWFpbC5jb20iLCJpYXQiOjE3MjEyNDA1MjMsImV4cCI6MTcyMTI0NDA2M30.s2Vxoff2aKUQFAVArM841gVrsyq14I0VAhW5mu1JqSw